# This file is auto-generated by scripts/generate_registry.sh. Do not edit manually.

declare -A INSTALLERS=(
    [agy]="Install Antigravity CLI"
    [bat]="Install Bat (alternative to cat) and configure alias"
    [node]="Install Node.js (LTS) and NVM"
    [nvim]="Install Neovim 0.11.7 and configuration"
    [pnpm]="Install pnpm package manager"
    [rust]="Install Rustup and Rust compiler/toolchain"
    [starship]="Install Starship shell prompt"
    [yay]="Install Yay AUR helper"
    [yazi]="Install Yazi terminal file manager and dependencies"
    [zoxide]="Install Zoxide directory jumper"
)

declare -A INSTALLER_DISPLAYS=(
    [agy]="Antigravity"
    [bat]="Bat"
    [node]="Node"
    [nvim]="Neovim"
    [pnpm]="Pnpm"
    [rust]="Rust"
    [starship]="Starship"
    [yay]="Yay"
    [yazi]="Yazi"
    [zoxide]="Zoxide"
)

INSTALLER_KEYS=(agy bat node nvim pnpm rust starship yay yazi zoxide)
