# This file is auto-generated by scripts/generate_registry.sh. Do not edit manually.

declare -A INSTALLERS=(
    [agy]="Antigravity CLI"
    [asciicinema]="asciinema terminal recorder"
    [bat]="Bat (alternative to cat) and configure alias"
    [docker]="Container runtime and orchestration platform"
    [lazygit]="Simple terminal UI for git commands"
    [node]="Node.js (LTS) and NVM"
    [nvim]="Neovim 0.12.0 and configuration"
    [pnpm]="pnpm package manager"
    [rust]="Rustup and Rust compiler/toolchain"
    [starship]="Starship shell prompt"
    [uv]="Fast Python package installer and resolver"
    [yay]="Yay AUR helper"
    [yazi]="Yazi terminal file manager and dependencies"
    [zoxide]="Zoxide directory jumper"
)

declare -A INSTALLER_DISPLAYS=(
    [agy]="Antigravity"
    [asciicinema]="asciicinema"
    [bat]="Bat"
    [docker]="Docker"
    [lazygit]="lazygit"
    [node]="Node"
    [nvim]="Neovim"
    [pnpm]="Pnpm"
    [rust]="Rust"
    [starship]="Starship"
    [uv]="uv"
    [yay]="Yay"
    [yazi]="Yazi"
    [zoxide]="Zoxide"
)

INSTALLER_KEYS=(agy asciicinema bat docker lazygit node nvim pnpm rust starship uv yay yazi zoxide)
